# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/rainbow/workspace/squeeze-words/assets/form.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_base_Widget(object):
    def setupUi(self, base_Widget):
        base_Widget.setObjectName("base_Widget")
        base_Widget.resize(599, 208)
        self.make_data_pushButton = QtWidgets.QPushButton(base_Widget)
        self.make_data_pushButton.setGeometry(QtCore.QRect(10, 10, 131, 32))
        self.make_data_pushButton.setObjectName("make_data_pushButton")
        self.clear_data_pushButton = QtWidgets.QPushButton(base_Widget)
        self.clear_data_pushButton.setGeometry(QtCore.QRect(10, 50, 131, 32))
        self.clear_data_pushButton.setObjectName("clear_data_pushButton")
        self.select_words_pushButton = QtWidgets.QPushButton(base_Widget)
        self.select_words_pushButton.setGeometry(QtCore.QRect(10, 90, 131, 32))
        self.select_words_pushButton.setObjectName("select_words_pushButton")
        self.start_review_pushButton = QtWidgets.QPushButton(base_Widget)
        self.start_review_pushButton.setGeometry(QtCore.QRect(10, 130, 131, 32))
        self.start_review_pushButton.setObjectName("start_review_pushButton")
        self.words_comboBox = QtWidgets.QComboBox(base_Widget)
        self.words_comboBox.setGeometry(QtCore.QRect(180, 10, 211, 32))
        self.words_comboBox.setObjectName("words_comboBox")

        self.retranslateUi(base_Widget)
        QtCore.QMetaObject.connectSlotsByName(base_Widget)

    def retranslateUi(self, base_Widget):
        _translate = QtCore.QCoreApplication.translate
        base_Widget.setWindowTitle(_translate("base_Widget", "Widget"))
        self.make_data_pushButton.setText(_translate("base_Widget", "生成数据"))
        self.clear_data_pushButton.setText(_translate("base_Widget", "清空数据"))
        self.select_words_pushButton.setText(_translate("base_Widget", "选择词本"))
        self.start_review_pushButton.setText(_translate("base_Widget", "开始复习"))
